services:
  proxy:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    volumes:
      - data:/data
      - config:/config
    networks:
      - proxy

volumes:
  data:
  config:

networks:
  proxy:
    name: cicd-proxy
    driver: bridge
