services:
  proxy:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    networks:
      - proxy

networks:
  proxy:
    name: cicd-proxy
    driver: bridge
